# Vectorizer + NaiveBayes Tuning

🎯 The goal of this challenge is to create a Pipeline combining a Vectorizer + a NaiveBayes algorithm and to fine-tune the pipeline.

✍️ Let's reuse the previous dataset with $2000$ reviews classified either as "positive" or "negative".

In [2]:
import pandas as pd

data = pd.read_csv("https://wagon-public-datasets.s3.amazonaws.com/05-Machine-Learning/10-Natural-Language-Processing/movie_reviews.csv")
data.head()

  target                                            reviews
0    neg  plot : two teen couples go to a church party ,...
1    neg  the happy bastard's quick movie review \ndamn ...
2    neg  it is movies like these that make a jaded movi...
3    neg   " quest for camelot " is warner bros . ' firs...
4    neg  synopsis : a mentally unstable man undergoing ...

In [3]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
data["target_encoded"] =  le.fit_transform(data.target)

In [4]:
data.head()

  target                                            reviews  target_encoded
0    neg  plot : two teen couples go to a church party ,...               0
1    neg  the happy bastard's quick movie review \ndamn ...               0
2    neg  it is movies like these that make a jaded movi...               0
3    neg   " quest for camelot " is warner bros . ' firs...               0
4    neg  synopsis : a mentally unstable man undergoing ...               0

## Preprocessing

❓ **Question (Cleaning)** ❓

Clean your texts

In [ ]:
import string
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer

def preprocessing(sentence):
    sentence = sentence.lower()
    sentence = ''.join(char for char in sentence if char not in string.punctuation)
    tokens=word_tokenize(sentence)
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    cleaned_sentence = ' '.join(tokens)
    return cleaned_sentence

In [10]:
# Clean reviews
data["clean_text"] = data["reviews"].apply(preprocessing)

## Tuning

❓ **Question (Pipelining a Vectorizer and a NaiveBayes Model)** ❓

* Create a Pipeline that chains a vectorizer of your choice with a NaiveBayes model
* Optimize it
* What is your best estimator ?

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import set_config; set_config("diagram")

# Create Pipeline
pipeline = Pipeline([
    ('tfidfvectorizer', TfidfVectorizer()),
    ('multinomialnb', MultinomialNB())
])

# Set parameters to search
parameters = {
    'tfidfvectorizer__ngram_range': [(1, 1), (1, 2)],
    'multinomialnb__alpha': [0.1, 0.5, 1]
}

# Perform grid search on pipeline
grid_search = GridSearchCV(
    pipeline,
    parameters,
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=1
)

grid_search.fit(data['clean_text'], data['target_encoded'])

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                                       ('multinomialnb', MultinomialNB())]),
             n_jobs=-1,
             param_grid={'multinomialnb__alpha': [0.1, 0.5, 1],
                         'tfidfvectorizer__ngram_range': [(1, 1), (1, 2)]},
             scoring='accuracy', verbose=1)

In [17]:
# YOUR CODE HERE
grid_search.best_estimator_
grid_search.best_params_
grid_search.best_score_

0.8275

🏁 Congratulations! You've managed to chain a Vectorizer and a NLP model and fine-tuned it!

💾 Don't forget to `git add/commit/push` your notebook...

🚀 ... and move on to the next challenge!